apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jwvne8bku-nodejs
  janus-idp.io/tekton: jwvne8bku-nodejs
  backstage.io/kubernetes-id: jwvne8bku-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: jwvne8bku-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
